# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 110af0df66e5fc615e4af0b939ccf61513de4c341ab5d58a241a3c704c7ff6971bf5509db14f4d2149f813040b0b2399f131636901948e24fb49bb12922b961a

test:
  secret_key_base: e78e7eb68e5b4e0f4a3c51b79e3e2814981bd54926e78f3aa886429ce81f03941c444606e39a4156c61e579704c27f0f59f7bde2752b43d397d0df1d29dec72e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
